# Uses SYBA to rank the ease of synthesis of organic molecules generated by rdkit
# This can detect bizarre/unrealistic conformations for review

from rdkit import Chem
import pandas as pd

from rdkit.Chem import RDConfig
import os
import sys
sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))
import sascorer as sa

def classify_mol(mol):
    
    if isinstance(mol, Chem.rdchem.Mol):
        res = sa.calculateScore(mol)
    else:
        res = 0
    
    return res

# To move to test
if __name__ == "__main__":
    df = pd.read_pickle('/home/spine/DProjects/DhydroEn/results/Dhydrocarbons/all_mols.pkl')
    df['sa_score'] = df['mol'].apply(classify_mol)
    # Molecules with an SA score < 3 are considered synthetically inaccessible
    df.to_pickle('/home/spine/DProjects/DhydroEn/results/Dhydrocarbons/all_mols_2.pkl')